-- Translate the role rights/permissions catalogue (profile_rights.prr_label) to
-- English. Labels only; codes (prr_tag) and ids untouched, so permissions keep
-- working. Re-runnable.
SET NAMES utf8mb4;
UPDATE profile_rights SET prr_label='Edit profile rights'                       WHERE prr_ser=1;
UPDATE profile_rights SET prr_label='Access the API page'                       WHERE prr_ser=2;
UPDATE profile_rights SET prr_label='List of records'                           WHERE prr_ser=3;
UPDATE profile_rights SET prr_label='Delete a record'                           WHERE prr_ser=4;
UPDATE profile_rights SET prr_label='Biological worklist'                       WHERE prr_ser=5;
UPDATE profile_rights SET prr_label='Biological validation'                     WHERE prr_ser=6;
UPDATE profile_rights SET prr_label='Grouped biological validation'             WHERE prr_ser=7;
UPDATE profile_rights SET prr_label='Technical worklist'                        WHERE prr_ser=8;
UPDATE profile_rights SET prr_label='Technical validation'                      WHERE prr_ser=9;
UPDATE profile_rights SET prr_label='Global report'                             WHERE prr_ser=10;
UPDATE profile_rights SET prr_label='New external request'                      WHERE prr_ser=11;
UPDATE profile_rights SET prr_label='New inpatient request'                     WHERE prr_ser=12;
UPDATE profile_rights SET prr_label='Status of samples in progress'             WHERE prr_ser=13;
UPDATE profile_rights SET prr_label='Result entry'                             WHERE prr_ser=14;
UPDATE profile_rights SET prr_label='Save a result'                            WHERE prr_ser=15;
UPDATE profile_rights SET prr_label='Download a worksheet'                      WHERE prr_ser=16;
UPDATE profile_rights SET prr_label='Add new analyses'                          WHERE prr_ser=17;
UPDATE profile_rights SET prr_label='Administrative record'                     WHERE prr_ser=18;
UPDATE profile_rights SET prr_label='Download a record attachment'              WHERE prr_ser=19;
UPDATE profile_rights SET prr_label='Download the transfer form'                WHERE prr_ser=20;
UPDATE profile_rights SET prr_label='Download record label'                     WHERE prr_ser=21;
UPDATE profile_rights SET prr_label='Download the invoice'                      WHERE prr_ser=22;
UPDATE profile_rights SET prr_label='Re-download a report'                      WHERE prr_ser=23;
UPDATE profile_rights SET prr_label='Reissue a report'                          WHERE prr_ser=24;
UPDATE profile_rights SET prr_label='Delete a record attachment'                WHERE prr_ser=25;
UPDATE profile_rights SET prr_label='Activity report'                           WHERE prr_ser=26;
UPDATE profile_rights SET prr_label='Epidemiological report'                    WHERE prr_ser=27;
UPDATE profile_rights SET prr_label='Indicators report'                         WHERE prr_ser=28;
UPDATE profile_rights SET prr_label='Statistical report'                        WHERE prr_ser=29;
UPDATE profile_rights SET prr_label='Turnaround time report'                    WHERE prr_ser=30;
UPDATE profile_rights SET prr_label='Pivot table'                               WHERE prr_ser=31;
UPDATE profile_rights SET prr_label='DHIS2 export'                              WHERE prr_ser=32;
UPDATE profile_rights SET prr_label='WHONET export'                             WHERE prr_ser=33;
UPDATE profile_rights SET prr_label='Patient history'                           WHERE prr_ser=34;
UPDATE profile_rights SET prr_label='Analysis history'                          WHERE prr_ser=35;
UPDATE profile_rights SET prr_label='End-of-day report'                         WHERE prr_ser=36;
UPDATE profile_rights SET prr_label='Daily billing status'                      WHERE prr_ser=37;
UPDATE profile_rights SET prr_label='Preferences'                               WHERE prr_ser=38;
UPDATE profile_rights SET prr_label='User management'                           WHERE prr_ser=39;
UPDATE profile_rights SET prr_label='Import users'                              WHERE prr_ser=40;
UPDATE profile_rights SET prr_label='Add a user'                                WHERE prr_ser=41;
UPDATE profile_rights SET prr_label='Analysis repository'                       WHERE prr_ser=42;
UPDATE profile_rights SET prr_label='Import the repository'                      WHERE prr_ser=43;
UPDATE profile_rights SET prr_label='Enable or disable an analysis'             WHERE prr_ser=44;
UPDATE profile_rights SET prr_label='Analysis status'                           WHERE prr_ser=45;
UPDATE profile_rights SET prr_label='Configure WHONET export for an analysis'   WHERE prr_ser=46;
UPDATE profile_rights SET prr_label='Edit analysis variable code'               WHERE prr_ser=47;
UPDATE profile_rights SET prr_label='Analyser configuration'                    WHERE prr_ser=48;
UPDATE profile_rights SET prr_label='Add an analyser'                           WHERE prr_ser=49;
UPDATE profile_rights SET prr_label='Edit an analyser'                          WHERE prr_ser=50;
UPDATE profile_rights SET prr_label='Delete an analyser'                        WHERE prr_ser=51;
UPDATE profile_rights SET prr_label='Dictionaries'                              WHERE prr_ser=52;
UPDATE profile_rights SET prr_label='Dictionary import'                         WHERE prr_ser=53;
UPDATE profile_rights SET prr_label='Backup configuration'                      WHERE prr_ser=54;
UPDATE profile_rights SET prr_label='Logo configuration'                        WHERE prr_ser=55;
UPDATE profile_rights SET prr_label='Age interval configuration'                WHERE prr_ser=56;
UPDATE profile_rights SET prr_label='Requesting service configuration'          WHERE prr_ser=57;
UPDATE profile_rights SET prr_label='Functional unit configuration'             WHERE prr_ser=58;
UPDATE profile_rights SET prr_label='Document template configuration'           WHERE prr_ser=59;
UPDATE profile_rights SET prr_label='Add a document template'                   WHERE prr_ser=60;
UPDATE profile_rights SET prr_label='Edit a document template'                  WHERE prr_ser=61;
UPDATE profile_rights SET prr_label='Test a document template'                  WHERE prr_ser=62;
UPDATE profile_rights SET prr_label='Delete a document template'                WHERE prr_ser=63;
UPDATE profile_rights SET prr_label='Report configuration'                      WHERE prr_ser=64;
UPDATE profile_rights SET prr_label='Record number configuration'               WHERE prr_ser=65;
UPDATE profile_rights SET prr_label='Manual configuration'                      WHERE prr_ser=66;
UPDATE profile_rights SET prr_label='Postal code configuration'                 WHERE prr_ser=67;
UPDATE profile_rights SET prr_label='Storage configuration'                     WHERE prr_ser=68;
UPDATE profile_rights SET prr_label='Form configuration'                        WHERE prr_ser=69;
UPDATE profile_rights SET prr_label='Patient record management'                 WHERE prr_ser=70;
UPDATE profile_rights SET prr_label='DHIS2 configuration'                       WHERE prr_ser=71;
UPDATE profile_rights SET prr_label='Add a DHIS2 API platform'                  WHERE prr_ser=72;
UPDATE profile_rights SET prr_label='Edit a DHIS2 API platform'                 WHERE prr_ser=73;
UPDATE profile_rights SET prr_label='Delete a DHIS2 API platform'               WHERE prr_ser=74;
UPDATE profile_rights SET prr_label='Epidemiology configuration'                WHERE prr_ser=75;
UPDATE profile_rights SET prr_label='Indicators report configuration'           WHERE prr_ser=76;
UPDATE profile_rights SET prr_label='General'                                   WHERE prr_ser=77;
UPDATE profile_rights SET prr_label='Laboratory'                                WHERE prr_ser=78;
UPDATE profile_rights SET prr_label='Add a laboratory'                          WHERE prr_ser=79;
UPDATE profile_rights SET prr_label='Download an org chart'                     WHERE prr_ser=80;
UPDATE profile_rights SET prr_label='Delete a laboratory'                       WHERE prr_ser=81;
UPDATE profile_rights SET prr_label='Staff'                                     WHERE prr_ser=82;
UPDATE profile_rights SET prr_label='Add a staff member'                        WHERE prr_ser=83;
UPDATE profile_rights SET prr_label='Edit a staff member'                       WHERE prr_ser=84;
UPDATE profile_rights SET prr_label='Export staff'                              WHERE prr_ser=85;
UPDATE profile_rights SET prr_label='Prescribers'                               WHERE prr_ser=86;
UPDATE profile_rights SET prr_label='Add a prescriber'                          WHERE prr_ser=87;
UPDATE profile_rights SET prr_label='Edit a prescriber'                         WHERE prr_ser=88;
UPDATE profile_rights SET prr_label='Delete a prescriber'                       WHERE prr_ser=89;
UPDATE profile_rights SET prr_label='Export prescribers'                        WHERE prr_ser=90;
UPDATE profile_rights SET prr_label='Suppliers'                                 WHERE prr_ser=91;
UPDATE profile_rights SET prr_label='Add a supplier'                            WHERE prr_ser=92;
UPDATE profile_rights SET prr_label='Edit a supplier'                           WHERE prr_ser=93;
UPDATE profile_rights SET prr_label='Delete a supplier'                         WHERE prr_ser=94;
UPDATE profile_rights SET prr_label='Export suppliers'                          WHERE prr_ser=95;
UPDATE profile_rights SET prr_label='Equipment'                                 WHERE prr_ser=96;
UPDATE profile_rights SET prr_label='Add equipment'                             WHERE prr_ser=97;
UPDATE profile_rights SET prr_label='Edit equipment'                            WHERE prr_ser=98;
UPDATE profile_rights SET prr_label='Delete equipment'                          WHERE prr_ser=99;
UPDATE profile_rights SET prr_label='Export equipment'                          WHERE prr_ser=100;
UPDATE profile_rights SET prr_label='Delete equipment file'                     WHERE prr_ser=101;
UPDATE profile_rights SET prr_label='Equipment – Document'                      WHERE prr_ser=102;
UPDATE profile_rights SET prr_label='Equipment – Maintenance'                   WHERE prr_ser=103;
UPDATE profile_rights SET prr_label='Add a maintenance'                         WHERE prr_ser=104;
UPDATE profile_rights SET prr_label='Delete a maintenance'                      WHERE prr_ser=105;
UPDATE profile_rights SET prr_label='Export maintenances'                       WHERE prr_ser=106;
UPDATE profile_rights SET prr_label='Delete maintenance file'                   WHERE prr_ser=107;
UPDATE profile_rights SET prr_label='Add a preventive maintenance'              WHERE prr_ser=108;
UPDATE profile_rights SET prr_label='Delete a preventive maintenance'           WHERE prr_ser=109;
UPDATE profile_rights SET prr_label='Export preventive maintenances'            WHERE prr_ser=110;
UPDATE profile_rights SET prr_label='Delete preventive maintenance file'        WHERE prr_ser=111;
UPDATE profile_rights SET prr_label='Equipment – Breakdown and repair'          WHERE prr_ser=112;
UPDATE profile_rights SET prr_label='Add a breakdown or repair'                 WHERE prr_ser=113;
UPDATE profile_rights SET prr_label='Delete a breakdown or repair'              WHERE prr_ser=114;
UPDATE profile_rights SET prr_label='Export breakdowns and repairs'             WHERE prr_ser=115;
UPDATE profile_rights SET prr_label='Delete breakdown/repair file'              WHERE prr_ser=116;
UPDATE profile_rights SET prr_label='Equipment – Metrology'                     WHERE prr_ser=117;
UPDATE profile_rights SET prr_label='Add a metrology or calibration'            WHERE prr_ser=118;
UPDATE profile_rights SET prr_label='Delete metrology/calibration file'         WHERE prr_ser=119;
UPDATE profile_rights SET prr_label='Manuals'                                   WHERE prr_ser=120;
UPDATE profile_rights SET prr_label='Add a manual'                              WHERE prr_ser=121;
UPDATE profile_rights SET prr_label='Edit a manual'                             WHERE prr_ser=122;
UPDATE profile_rights SET prr_label='Delete a manual'                           WHERE prr_ser=123;
UPDATE profile_rights SET prr_label='Export manuals'                            WHERE prr_ser=124;
UPDATE profile_rights SET prr_label='Delete manual file'                        WHERE prr_ser=125;
UPDATE profile_rights SET prr_label='Procedures'                                WHERE prr_ser=126;
UPDATE profile_rights SET prr_label='Procedure consultation table'              WHERE prr_ser=127;
UPDATE profile_rights SET prr_label='Add a procedure'                           WHERE prr_ser=128;
UPDATE profile_rights SET prr_label='Edit a procedure'                          WHERE prr_ser=129;
UPDATE profile_rights SET prr_label='Delete a procedure'                        WHERE prr_ser=130;
UPDATE profile_rights SET prr_label='Export procedures'                         WHERE prr_ser=131;
UPDATE profile_rights SET prr_label='Delete procedure file'                     WHERE prr_ser=132;
UPDATE profile_rights SET prr_label='Stock management'                          WHERE prr_ser=133;
UPDATE profile_rights SET prr_label='Add a product'                             WHERE prr_ser=134;
UPDATE profile_rights SET prr_label='Edit a product'                            WHERE prr_ser=135;
UPDATE profile_rights SET prr_label='Delete a product'                          WHERE prr_ser=136;
UPDATE profile_rights SET prr_label='Export products'                           WHERE prr_ser=137;
UPDATE profile_rights SET prr_label='History of this product'                   WHERE prr_ser=138;
UPDATE profile_rights SET prr_label='Record quantity used'                      WHERE prr_ser=139;
UPDATE profile_rights SET prr_label='Stock cancellation'                        WHERE prr_ser=140;
UPDATE profile_rights SET prr_label='Remove an empty stock line'                WHERE prr_ser=141;
UPDATE profile_rights SET prr_label='Product catalogue'                         WHERE prr_ser=142;
UPDATE profile_rights SET prr_label='Non-conformity modules'                    WHERE prr_ser=143;
UPDATE profile_rights SET prr_label='Add a non-conformity'                      WHERE prr_ser=144;
UPDATE profile_rights SET prr_label='Edit a non-conformity'                     WHERE prr_ser=145;
UPDATE profile_rights SET prr_label='Delete a non-conformity'                   WHERE prr_ser=146;
UPDATE profile_rights SET prr_label='Export non-conformities'                   WHERE prr_ser=147;
UPDATE profile_rights SET prr_label='Non-conformity follow-up'                  WHERE prr_ser=148;
UPDATE profile_rights SET prr_label='Set up a corrective action'                WHERE prr_ser=149;
UPDATE profile_rights SET prr_label='Close the non-conformity'                  WHERE prr_ser=150;
UPDATE profile_rights SET prr_label='Internal quality control'                  WHERE prr_ser=151;
UPDATE profile_rights SET prr_label='Add an internal control'                   WHERE prr_ser=152;
UPDATE profile_rights SET prr_label='Edit an internal control'                  WHERE prr_ser=153;
UPDATE profile_rights SET prr_label='Export internal controls'                  WHERE prr_ser=154;
UPDATE profile_rights SET prr_label='Add an internal control result'            WHERE prr_ser=155;
UPDATE profile_rights SET prr_label='Export internal control results'           WHERE prr_ser=156;
UPDATE profile_rights SET prr_label='External quality control'                  WHERE prr_ser=157;
UPDATE profile_rights SET prr_label='Add an external control'                   WHERE prr_ser=158;
UPDATE profile_rights SET prr_label='Edit an external control'                  WHERE prr_ser=159;
UPDATE profile_rights SET prr_label='Export external controls'                  WHERE prr_ser=160;
UPDATE profile_rights SET prr_label='Add an external control result'            WHERE prr_ser=161;
UPDATE profile_rights SET prr_label='Export external control results'           WHERE prr_ser=162;
UPDATE profile_rights SET prr_label='Laboratory meeting'                        WHERE prr_ser=163;
UPDATE profile_rights SET prr_label='Add a meeting'                             WHERE prr_ser=164;
UPDATE profile_rights SET prr_label='Edit a meeting'                            WHERE prr_ser=165;
UPDATE profile_rights SET prr_label='Delete a meeting'                          WHERE prr_ser=166;
UPDATE profile_rights SET prr_label='Export meetings'                           WHERE prr_ser=167;
UPDATE profile_rights SET prr_label='Delete meeting file'                       WHERE prr_ser=168;
UPDATE profile_rights SET prr_label='Sample management'                         WHERE prr_ser=169;
UPDATE profile_rights SET prr_label='Add an item'                               WHERE prr_ser=170;
UPDATE profile_rights SET prr_label='Edit an item'                              WHERE prr_ser=171;
UPDATE profile_rights SET prr_label='Destock an item'                           WHERE prr_ser=172;
UPDATE profile_rights SET prr_label='Delete an item'                            WHERE prr_ser=173;
UPDATE profile_rights SET prr_label='Printer configuration'                     WHERE prr_ser=174;
UPDATE profile_rights SET prr_label='LabBook Lite configuration'                WHERE prr_ser=175;
UPDATE profile_rights SET prr_label='Send the report'                           WHERE prr_ser=176;
UPDATE profile_rights SET prr_label='List of dispatches'                        WHERE prr_ser=177;
UPDATE profile_rights SET prr_label='Sending method configuration'              WHERE prr_ser=178;
UPDATE profile_rights SET prr_label='Automation configuration'                  WHERE prr_ser=179;
UPDATE profile_rights SET prr_label='Add an item'                               WHERE prr_ser=180;
UPDATE profile_rights SET prr_label='Edit an item'                              WHERE prr_ser=181;
UPDATE profile_rights SET prr_label='Delete an item'                            WHERE prr_ser=182;
UPDATE profile_rights SET prr_label='View the audit log'                        WHERE prr_ser=183;
