[program:logrotate_labbook]
command = /bin/bash /home/supervisor/etc/logrotate_labbook.sh
directory = /home/supervisor/etc
autostart = true
autorestart = true
startsecs = 5
startretries = 3
stdout_logfile = /home/supervisor/log/logrotate_labbook.stdout.log
stderr_logfile = /home/supervisor/log/logrotate_labbook.stderr.log
